environments:
  - name: {Environment Name}
    host: {S3 endpoint}
    port: {s3 listening port}
    secure: {using secured protocol}
    pathStyle: {using pathStyle}
    accessKey: {accessKey}
    secretKey: {secretKey}
  - name: {Environment Name}
    host: {S3 endpoint}
    port: {s3 listening port}
    secure: {using secured protocol}
    pathStyle: {using pathStyle}
    accessKey: {accessKey}
    secretKey:  {secretKey}
